#!/bin/bash

# Scott Alan Miller's CentOS 7 Rocket.Chat Build Script
# scott@ntg.co
#
# Discuss at http://mangolassi.it/topic/8086/installing-rocket-chat-on-centos-7

cat > /etc/yum.repos.d/mongodb.repo <<EOF
[mongodb]
name=MongoDB Repository
baseurl=http://downloads-distro.mongodb.org/repo/redhat/os/x86_64
gpgcheck=0
enabled=1
EOF

yum install -y epel-release firewalld
yum install -y nodejs curl GraphicsMagick npm mongodb-org-server mongodb-org policycoreutils-python
semanage port -a -t mongod_port_t -p tcp 27017
systemctl start mongod
systemctl enable mongod
firewall-cmd --zone=public --add-port=80/tcp --permanent
firewall-cmd --reload
npm install -g inherits n
n 4.5
cd /opt
curl -L https://rocket.chat/releases/latest/download -o rocket.chat.tgz
tar zxvf rocket.chat.tgz
mv bundle Rocket.Chat
cd Rocket.Chat/programs/server
npm install
cd ../..
npm install forever
echo "export ROOT_URL=http://rocket/" >> ~/.bashrc
echo "export MONGO_URL=mongodb://localhost:27017/rocketchat" >> ~/.bashrc
echo "export PORT=80" >> ~/.bashrc
source ~/.bashrc
/opt/Rocket.Chat/node_modules/forever/bin/forever start /opt/Rocket.Chat/main.js
